// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyQM5fmmF9PnNVfcOqLNmXrZF0tmj06eA',
    appId: '1:318256480448:android:d376dbc6d4241ffe5e2d25',
    messagingSenderId: '318256480448',
    projectId: 'connectvn-acd36',
    storageBucket: 'connectvn-acd36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9zOHrQZkqAVVXHTCtcnk2bVX1d1KZSZM',
    appId: '1:318256480448:ios:d27c4d77b7ed8c1c5e2d25',
    messagingSenderId: '318256480448',
    projectId: 'connectvn-acd36',
    storageBucket: 'connectvn-acd36.appspot.com',
    androidClientId:
        '318256480448-ve2nep050npdmr4c2fjeck0e4t5vi55f.apps.googleusercontent.com',
    iosClientId:
        '318256480448-dm0b2498stgm29thinjsimtdelfjsi45.apps.googleusercontent.com',
    iosBundleId: 'com.muonroi.truyentm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9zOHrQZkqAVVXHTCtcnk2bVX1d1KZSZM',
    appId: '1:318256480448:ios:d27c4d77b7ed8c1c5e2d25',
    messagingSenderId: '318256480448',
    projectId: 'connectvn-acd36',
    storageBucket: 'connectvn-acd36.appspot.com',
    androidClientId:
        '318256480448-ve2nep050npdmr4c2fjeck0e4t5vi55f.apps.googleusercontent.com',
    iosClientId:
        '318256480448-dm0b2498stgm29thinjsimtdelfjsi45.apps.googleusercontent.com',
    iosBundleId: 'com.muonroi.truyentm',
  );
}
